export const contractFieldCoords = {
  lessee: {
    entityName: {
      page: 0,
      x: 82,
      y: 648,
      fontSize: 10,
      clearWidth: 320,
      clearHeight: 20,
      clearOffsetX: -4,
      clearOffsetY: -7,
    },
    installationAddress: {
      page: 0,
      x: 82,
      y: 625,
      fontSize: 10,
      clearWidth: 320,
      clearHeight: 24,
      clearOffsetX: -4,
      clearOffsetY: -8,
    },
    phone: {
      page: 0,
      x: 82,
      y: 598,
      fontSize: 10,
      clearWidth: 230,
      clearHeight: 18,
      clearOffsetX: -4,
      clearOffsetY: -6,
    },
    email: {
      page: 0,
      x: 82,
      y: 579,
      fontSize: 10,
      clearWidth: 260,
      clearHeight: 18,
      clearOffsetX: -4,
      clearOffsetY: -6,
    },
    abn: {
      page: 0,
      x: 82,
      y: 560,
      fontSize: 10,
      clearWidth: 230,
      clearHeight: 18,
      clearOffsetX: -4,
      clearOffsetY: -6,
    },
  },
  supplier: {
    name: {
      page: 0,
      x: 350,
      y: 648,
      fontSize: 10,
      clearWidth: 240,
      clearHeight: 20,
      clearOffsetX: -4,
      clearOffsetY: -7,
    },
    address: {
      page: 0,
      x: 350,
      y: 625,
      fontSize: 10,
      clearWidth: 240,
      clearHeight: 24,
      clearOffsetX: -4,
      clearOffsetY: -8,
    },
    abn: {
      page: 0,
      x: 350,
      y: 604,
      fontSize: 10,
      clearWidth: 220,
      clearHeight: 18,
      clearOffsetX: -4,
      clearOffsetY: -6,
    },
    phone: {
      page: 0,
      x: 350,
      y: 584,
      fontSize: 10,
      clearWidth: 180,
      clearHeight: 18,
      clearOffsetX: -4,
      clearOffsetY: -6,
    },
    email: {
      page: 0,
      x: 350,
      y: 566,
      fontSize: 10,
      clearWidth: 240,
      clearHeight: 18,
      clearOffsetX: -4,
      clearOffsetY: -6,
    },
  },
  equipmentDescriptions: [
    {
      page: 0,
      x: 82,
      y: 500,
      fontSize: 9,
      clearWidth: 280,
      clearHeight: 18,
      clearOffsetX: -3,
      clearOffsetY: -5,
    },
    {
      page: 0,
      x: 82,
      y: 476,
      fontSize: 9,
      clearWidth: 280,
      clearHeight: 18,
      clearOffsetX: -3,
      clearOffsetY: -5,
    },
    {
      page: 0,
      x: 82,
      y: 452,
      fontSize: 9,
      clearWidth: 280,
      clearHeight: 18,
      clearOffsetX: -3,
      clearOffsetY: -5,
    },
  ],
  equipmentQuantities: [
    {
      page: 0,
      x: 332,
      y: 500,
      fontSize: 9,
      clearWidth: 45,
      clearHeight: 18,
      clearOffsetX: -2,
      clearOffsetY: -5,
    },
    {
      page: 0,
      x: 332,
      y: 476,
      fontSize: 9,
      clearWidth: 45,
      clearHeight: 18,
      clearOffsetX: -2,
      clearOffsetY: -5,
    },
    {
      page: 0,
      x: 332,
      y: 452,
      fontSize: 9,
      clearWidth: 45,
      clearHeight: 18,
      clearOffsetX: -2,
      clearOffsetY: -5,
    },
  ],
  finance: {
    monthlyPayment: {
      page: 0,
      x: 428,
      y: 508,
      fontSize: 10,
      clearWidth: 170,
      clearHeight: 20,
      clearOffsetX: -4,
      clearOffsetY: -6,
    },
    term: {
      page: 0,
      x: 553,
      y: 472,
      fontSize: 10,
      clearWidth: 50,
      clearHeight: 18,
      clearOffsetX: -2,
      clearOffsetY: -5,
    },
    specialConditions: {
      page: 0,
      x: 82,
      y: 348,
      fontSize: 9,
      clearWidth: 480,
      clearHeight: 78,
      clearOffsetX: -4,
      clearOffsetY: -10,
      lineHeight: 12,
      maxCharsPerLine: 80,
    },
  },
  directors: [
    {
      name: {
        page: 0,
        x: 82,
        y: 258,
        fontSize: 10,
        clearWidth: 220,
        clearHeight: 18,
        clearOffsetX: -3,
        clearOffsetY: -5,
      },
      position: {
        page: 0,
        x: 82,
        y: 236,
        fontSize: 10,
        clearWidth: 220,
        clearHeight: 18,
        clearOffsetX: -3,
        clearOffsetY: -5,
      },
      date: {
        page: 0,
        x: 268,
        y: 216,
        fontSize: 10,
        clearWidth: 110,
        clearHeight: 18,
        clearOffsetX: -3,
        clearOffsetY: -5,
      },
    },
    {
      name: {
        page: 0,
        x: 350,
        y: 258,
        fontSize: 10,
        clearWidth: 220,
        clearHeight: 18,
        clearOffsetX: -3,
        clearOffsetY: -5,
      },
      position: {
        page: 0,
        x: 350,
        y: 236,
        fontSize: 10,
        clearWidth: 220,
        clearHeight: 18,
        clearOffsetX: -3,
        clearOffsetY: -5,
      },
      date: {
        page: 0,
        x: 525,
        y: 216,
        fontSize: 10,
        clearWidth: 100,
        clearHeight: 18,
        clearOffsetX: -3,
        clearOffsetY: -5,
      },
    },
  ],
  signature: { page: 1, x: 150, y: 180, width: 200, height: 60 },
} as const;
