export const contractFieldCoords = {
  businessName: {
    page: 0,
    x: 120,
    y: 700,
    fontSize: 10,
    clearWidth: 320,
    clearHeight: 16,
    clearOffsetX: -8,
    clearOffsetY: -6,
  },
  abnNumber: {
    page: 0,
    x: 120,
    y: 685,
    fontSize: 10,
    clearWidth: 320,
    clearHeight: 16,
    clearOffsetX: -8,
    clearOffsetY: -6,
  },
  businessAddress: {
    page: 0,
    x: 120,
    y: 670,
    fontSize: 10,
    clearWidth: 420,
    clearHeight: 16,
    clearOffsetX: -8,
    clearOffsetY: -6,
  },
  financeAmount: {
    page: 0,
    x: 420,
    y: 700,
    fontSize: 10,
    clearWidth: 180,
    clearHeight: 16,
    clearOffsetX: -6,
    clearOffsetY: -6,
  },
  term: {
    page: 0,
    x: 420,
    y: 685,
    fontSize: 10,
    clearWidth: 180,
    clearHeight: 16,
    clearOffsetX: -6,
    clearOffsetY: -6,
  },
  signature: { page: 1, x: 150, y: 180, width: 200, height: 60 },
} as const;
